name: maarchrmap_norif
version: '3'
services:
    maarchrmap:
        container_name: maarchrmap_norif
        build:
        context: .
        dockerfile: Dockerfile
        ports:
        - "9090:80"
        - "5433:5432"
        volumes:
        - ./:/var/www/laabs/

    maarchrmap_notif:
        container_name: maarchrmap_notif
        image: essejacquesdansomon/maarchrmap_notif
        environment:
          - API_URL=localhost
          - NOTIFICATION_BASH_ID=maarchRMAP_sd255i-36u0-8ifhch
          - LAABS_AUTH=1